Fix out of bounds read in slarrv
Reference-LAPACK/lapack pull request #625
Opened 2021-09-30 07:56 UTC by Keno

This was originally reported as https://github.com/JuliaLang/julia/issues/42415.
I've tracked this down to an our of bounds read on the following line:

https://github.com/Reference-LAPACK/lapack/blob/44ecb6a5ff821b1cbb39f8cc2166cb098e060b4d/SRC/slarrv.f#L423

In the crashing example, `M` is `0`, causing `slarrv` to read uninitialized
memory from the work array. I believe the `0` for `M` is correct and indeed,
the documentation above supports that `M` may be zero:

https://github.com/Reference-LAPACK/lapack/blob/44ecb6a5ff821b1cbb39f8cc2166cb098e060b4d/SRC/slarrv.f#L113-L116

I believe it may be sufficient to early-out this function as suggested
in this PR. However, I have limited context for the full routine here,
so I would appreciate a sanity check.

2021-09-30 09:13 UTC, andreasnoack commented
It looks right to but it might make sense to move this check to https://github.com/Reference-LAPACK/lapack/blob/44ecb6a5ff821b1cbb39f8cc2166cb098e060b4d/SRC/slarrv.f#L353-L355 where there is already an early exit check.

This issue was found in https://github.com/JuliaLang/julia/issues/42415, i.e. the original call was from `sstemr` and this seems to happen when requesting eigenvectors corresponding to an interval that doesn't contain any eigenvalues.

This PR only fixes the `s` version of `xlarrv` so if the fix is considered correct then similar changes should be made to the `d`, `c`, and `z` versions.

2021-09-30 16:38 UTC, langou approved these changes

2021-09-30 16:39 UTC, martin-frbg requested changes
Looks good to me (with the change suggested by andreasnoack, to move the exit to the start of the function where we already check for N.LE.0 )

2021-09-30 21:53 UTC, weslleyspereira commented
I agree with @martin-frbg and @andreasnoack. Could you do this slightly modification, @Keno? Thanks a lot.

2021-10-01 00:29 UTC, Keno commented
I updated the PR.

2021-10-01 09:12 UTC, martin-frbg approved these changes

2021-10-01 14:27 UTC, merged

2021-10-01 14:46 UTC, weslleyspereira commented
Thanks!! I've just merged it.

2021-10-01 14:53 UTC, langou commented
Thanks @Keno. Excellent!

2021-12-06 10:18 UTC, thoger commented
We got an info that VulnDB is flagging this fix as a security issue.  The relevant VulnDB link should be:

https://vulndb.cyberriskanalytics.com/vulnerabilities/270365

and should include the following description:

> OpenBLAS contains an out-of-bounds read error in the zlarrv.f library that occurs when user input is not validated properly. This could allow a remote attacker to crash the process associated with the library, or potentially expose the contents of memory by executing arbitrary code.

Note that it's flagging OpenBLAS as affected, not lapack directly, but the relevant file is the lapack code bundled in OpenBLAS.

However, this information is part of the VulnDB subscriber-only content and I do not have access to it, we only got this information indirectly.

AFAICT, there was no CVE assigned for the issue.  I'd like to ask if you have any concerns with getting a CVE assigned here as the issue is already getting flagged as a vulnerability.  Any thoughts on how likely this issue may be triggered in a real-world use cases via untrusted inputs to a non-malicious applications?

2021-12-06 11:34 UTC, Keno commented
It is an out of bounds read, so it does qualify as the kind of vulnerability CVEs are issued for if someone wanted to write that up and submit it. Not sure how likely it is that someone is taking untrusted matrices and running a symmetric tridiag eigensolve on them, which is a bit of a niche thing to do, but if you are, crafting a malicious input is pretty easy.

2021-12-10 11:08 UTC, thoger commented
Thank you!  CVE-2021-4048 was assigned.

https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-4048

2022-10-07 21:04 UTC, ValZapod commented
OneMKL only now mrged the fix. https://www.intel.com/content/www/us/en/developer/articles/release-notes/onemkl-release-notes.html